name: easyRTP
version: "2.0.0"
main: lol.sander.easyRTP.EasyRTP
api-version: '1.21'
authors: [ sanderson ]
website: sander.lol

commands:
  test:
    description: Hi
  rtp:
    permission: easyrtp.rtp
    description: Teleports you randomly
  easyrtp:
    description: Shows configuration

permissions:
  easyrtp.rtp:
    description: RTP command permission
    default: true
