name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jar
          path: build/libs/*.jar

  release:
    runs-on: ubuntu-latest
    needs: build
  
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
  
      - name: Get commit hash
        id: get_commit
        run: echo "::set-output name=COMMIT_HASH::$(git rev-parse --short HEAD)"
  
      - name: Configure Git for pushing with PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://$GITHUB_ACTOR:$PAT_TOKEN@github.com/$GITHUB_REPOSITORY.git
  
      - name: Create and push tag
        run: |
          TAG_NAME="${{ steps.get_commit.outputs.COMMIT_HASH }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME
  
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          tag_name: ${{ steps.get_commit.outputs.COMMIT_HASH }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
